imports:
  - { resource: vendor/user/profile/services.yaml }
  - { resource: vendor/communication/member-list/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  User\Auth\:
    resource: './src/*'

  User\Auth\AuthService:
    alias: User\Auth\Service\Auth
    public: true

# private
