imports:
  - { resource: vendor/user/auth/services.yaml }
  - { resource: vendor/user/profile/services.yaml }

services:
  _defaults:
    autowire: true

  _instanceof:
    Web\Controller:
      tags: [Web\Controller]
      public: true

  Web\User\:
    resource: './src/*'
