imports:
  - { resource: ../../user/auth/services.yml }
  - { resource: ../../user/profile/services.yml }

services:
  _defaults:
    autowire: true

  _instanceof:
    Web\Controller:
      tags: [Web\Controller]
      public: true

  Web\User\:
    resource: './src/*'
