imports:
  - { resource: vendor/communication/member-list/services.yaml }
  - { resource: vendor/communication/messages/services.yaml }
  - { resource: vendor/communication/messages-storage/services.yaml } # <- composition

services:
  _defaults:
    autowire: true

  _instanceof:
    Web\Controller:
      tags: [Web\Controller]
      public: true

  Web\Communication\:
    resource: './src/*'
